---
services:
  # kafka:
  #   #image: ghcr.io/s24-capstone-distributed/tradeserverkafka:latest
  #   image: confluentinc/cp-kafka:latest
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 9092:9092
  #   environment:
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://192.168.8.144:9092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_CREATE_TOPICS: "MarketValueTopic:1:1"
  #   networks:
  #     - ${NETWORK}

  hazelcast:
    build: ./HazelCast
    environment:
      - HAZELCAST_CLUSTER_NAME=t1_hazelcast
    expose:
      - 5701
    networks:
      - ${NETWORK}
    
  blotterservice1:
    build: ./BlotterService
    environment:
      - HTTP_PORT=8010
      - TCP_PORT=8012
      - CLIENT_CONNECTIONS_MAP=clients
      - HAZELCAST_CLUSTER_NAME=t1_hazelcast
      - HAZELCAST_SERVERS=hazelcast:5701
      - MONGO_CONNECTION=mongodb://${MONGO_IP}:${MONGO_PORT}
      - MONGO_DB_NAME=tradeServer
      - MONGO_COLLECTION=marketValue
      - HOSTNAME=blotterservice1
      - EXTERNAL_HOST=${CLIENT_ACCESS_HOST} #Refer to infrastructure machine
      - GRAFANA_URL=${GRAFANA_HOST}:${GRAFANA_PORT} # this will be changed
    depends_on:
      #- kafka
      - hazelcast
    networks:
      - ${NETWORK}
    ports:
      - 8010:8010
    expose:
      - 8012
    restart: always

  blotterservice2:
    build: ./BlotterService
    environment:
      - HTTP_PORT=8020
      - TCP_PORT=8022
      - CLIENT_CONNECTIONS_MAP=clients
      - HAZELCAST_CLUSTER_NAME=t1_hazelcast
      - HAZELCAST_SERVERS=hazelcast:5701
      - MONGO_CONNECTION=mongodb://${MONGO_IP}:${MONGO_PORT}
      - MONGO_DB_NAME=tradeServer
      - MONGO_COLLECTION=marketValue
      - HOSTNAME=blotterservice2
      - EXTERNAL_HOST=${CLIENT_ACCESS_HOST} #Refer to infrastructure machine
      - GRAFANA_URL=${GRAFANA_HOST}:${GRAFANA_PORT} # this will be changed
    depends_on:
      # - kafka
      - hazelcast
    networks:
      - ${NETWORK}
    ports:
      - 8020:8020
    expose:
      - 8022
    restart: always

  blotterservice3:
    build: ./BlotterService
    environment:
      - HTTP_PORT=8030
      - TCP_PORT=8032
      - CLIENT_CONNECTIONS_MAP=clients
      - HAZELCAST_CLUSTER_NAME=t1_hazelcast
      - HAZELCAST_SERVERS=hazelcast:5701
      - MONGO_CONNECTION=mongodb://${MONGO_IP}:${MONGO_PORT}
      - MONGO_DB_NAME=tradeServer
      - MONGO_COLLECTION=marketValue
      - HOSTNAME=blotterservice3
      - EXTERNAL_HOST=${CLIENT_ACCESS_HOST} #Refer to infrastructure machine
      - GRAFANA_URL=${GRAFANA_HOST}:${GRAFANA_PORT} # this will be changed
    depends_on:
      # - kafka
      - hazelcast
    networks:
      - ${NETWORK}
    ports:
      - 8030:8030
    expose:
      - 8032
    restart: always

  cdrs:
    build: ./ClientDataRoutingService
    depends_on:
     # - kafka
      - hazelcast
      - blotterservice1
      - blotterservice2
      - blotterservice3
    environment:
      - BOOTSTRAP_SERVERS=${KAFKA_HOST}:${KAFKA_PORT}
      - MARKET_VALUE_TOPIC=MarketValueTopic
      - HAZELCAST_CLUSTER_NAME=t1_hazelcast
      - HAZELCAST_INSTANCE_NAME=CDRS_1
      - HAZELCAST_SERVERS=hazelcast:5701
      - CLIENT_CONNECTIONS_MAP=clients
    networks:
      - ${NETWORK}

  gateway1:
    build: ./Gateway/
    environment:
      - port=6010
      - HAZELCAST_CLUSTER_NAME=t1_hazelcast
      - HAZELCAST_SERVERS=hazelcast:5701
      - CLIENT_CONNECTIONS_MAP=clients
      - GRAFANA_URL=${GRAFANA_HOST}:${GRAFANA_PORT}
    expose:
      - 6010:6010
    depends_on:
      - hazelcast
    networks:
      - ${NETWORK}
    restart: always

  gateway2:
    build: ./Gateway/
    environment:
      - port=6020
      - HAZELCAST_CLUSTER_NAME=t1_hazelcast
      - HAZELCAST_SERVERS=hazelcast:5701
      - CLIENT_CONNECTIONS_MAP=clients
      - GRAFANA_URL=${GRAFANA_HOST}:${GRAFANA_PORT}
    depends_on:
      - hazelcast
    expose:
      - 6020:6020
    networks:
      - ${NETWORK}
    restart: always

  haproxy:
    build: ./HAProxy/
    networks:
      - ${NETWORK}
    depends_on:
     - gateway1
     - gateway2
    ports:
      - 80:80

  #TESTING PURPOSES ONLY, TO BE REMOVED
  # producer:
  #   build: 
  #     context: ./ClientDataRoutingService/
  #     dockerfile: producer.Dockerfile
  #   depends_on:
  #     - kafka
  #     - haproxy
  #   environment:
  #     - BOOTSTRAP_SERVERS=kafka:29092
  #     - MARKET_VALUE_TOPIC=MarketValueTopic
  #     - CLIENT_ID=17
  #   networks:
  #     - ${NETWORK}


  # kafka-ui:
  #   container_name: kafka-ui
  #   image: provectuslabs/kafka-ui:latest
  #   ports:
  #     - 8080:8080
  #   environment:
  #     DYNAMIC_CONFIG_ENABLED: 'true'
  #   # volumes:
  #   #   - .\config.yml:/etc/kafkaui/dynamic_config.yaml
  #   networks:
  #     - ${NETWORK}
  
networks:
  't1-network':